### ISSUE TITLE
Error when setting the days of the year in a one year analysis

### ISSUE THREAD

**Issue by oguzhannysr** [SMByC/CCD-Plugin#9] opened 2023-12-15 10:00 UTC
@XavierCLL @danielm09 ,What is the reason for this problem? I could not draw the time series.

Traceback (most recent call last):
  File "C:\Users/yasar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\CCD_Plugin\utils\system_utils.py", line 35, in wrapper
    return func(*args, **kwargs)
  File "C:\Users/yasar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\CCD_Plugin\utils\system_utils.py", line 91, in wrapper
    obj_returned = func(*args, **kwargs)
  File "C:\Users/yasar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\CCD_Plugin\gui\CCD_Plugin_dockwidget.py", line 170, in new_plot
    self.html_file = generate_plot(ccdc_result_info, timeseries, date_range, dataset, band_or_index, CCD_Plugin.tmp_dir)
  File "C:\Users/yasar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\CCD_Plugin\core\plot.py", line 97, in generate_plot
    datetime_min = datetime.fromtimestamp(np.min(dates_obs) / 1000)
  File "<__array_function__ internals>", line 200, in amen
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\numpy\core\fromnumeric.py", line 2946, in amen
    return _wrapreduction(a, np.minimum, 'min', axis, None, out,
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\numpy\core\fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
numpy.core._exceptions._UFuncNoLoopError: ufunc 'minimum' did not contain a loop with signature matching types (dtype('<U38'), dtype('<U38')) -> None

My google earth engine code:
import ee
from ee_plugin import Map

image = ee.ImageCollection('COPERNICUS/S2') \
  .filterDate('2019-06-01', '2020-07-02')  
  
Map.addLayer(image, 'S2')

![image](https://github.com/SMByC/CCD-Plugin/assets/53774968/0d8dd6a8-a700-42a8-b113-8741c3d1e4f8)

**Comment by XavierCLL** [comment] 2023-12-16 15:51
Hi @oguzhannysr 

The issue is because `Days of year` parameter, this option is mostly for multi-year analysis but not for a one-year date range. Then reset to 1-365, this is my test for the same location and options:

![image](https://github.com/SMByC/CCD-Plugin/assets/11801453/45d241e1-b573-430d-9632-3516bb66d612)

But I need to put some messages or manage that situation better in the plugin.

Regards
Xavier

**Comment by oguzhannysr** [comment] 2023-12-18 15:23
@XavierCLL ,Great, it worked, thank you. Now I want to look at the upcoming 20000 points in the region I will analyze. It would be very time-consuming to visually check which one has changed. What can I do for this? Is there a shortcut? How can I bulk produce time series for a region? A button to download time series in CSV format would also be great.

**Comment by danielm09** [comment] 2023-12-18 15:45
Hi @oguzhannysr . The plugin was not created for the purpose of processing CCD for a group of pixels. Instead, it was intended to provide a quick way to visualize the regression adjustment at a single point. If you want to retrieve CCD's results for a group of points or acquire their time series, I suggest you do that directly on Google Earth Engine.

If you want to produce a map of pixels that changed according to CCD, you can check this [post](https://medium.com/@moraesd90/detecting-change-with-ccdc-on-google-earth-engine-7125bfc1a6a).
I hope that helps.

**Comment by XavierCLL** [comment] 2023-12-18 21:59
Changing the title to have a better reference of the original problem and closing, fixed with dcf183e8f64012d7911ddb03e650428e6c6ae1e0

**Closed as completed by XavierCLL** 2023-12-18 21:59 UTC
